import { describe, it, expect } from 'vitest'
import {
  assertLooksLikePicksheet,
  PicksheetAuthError,
  PicksheetNotReadyError
} from './picksheet-content'

const WEEK_ID = 671

/**
 * Fixtures are the ACTUAL responses observed from officefootballpool.com during
 * debugging, not invented text. Each previously slipped through the old
 * `text.length < 100` guard and would have been stored as a real picksheet.
 */

// Observed when the CloudFront WAF blocked headless Chrome (~513 chars).
const CLOUDFRONT_403 = `403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time.
There might be too much traffic or a configuration error.
Generated by cloudfront (CloudFront)
Request ID: 8r7V3Q205v0h4WRxES4UpZCRK2wL5BWfR0XbenPf3ICS`

// Observed when the session was not recognised (~20KB page, abridged here).
const LOGGED_OUT = `Our sites Log In Pools Picks Standings Analysis Pool Admin Pool Settings Help
Printable Picksheet You need to be logged in to use this page.
Log In OR Don't have an account? Sign Up New Login Process!`

// Observed by an AUTHENTICATED user before the pool manager posted the schedule.
const NO_GAMES_YET = `Printable Picksheet
Sorry, there are no games for this week. Please check back later after your
pool manager has set the schedule.`

const REAL_PICKSHEET = `NFL Week 1 | College 2 Picksheet
 1 pt     Dallas (7-10) +7.5    Thu 5:20 PM    PHILADELPHIA (18-3) -7.5
 1 pt     Kansas City (17-3) -3.5    Fri 5:00 PM    LA CHARGERS (11-7) +3.5
 1 pt     Tampa Bay (10-8) -2.5    Sun 10:00 AM    ATLANTA (8-9) +2.5`

describe('assertLooksLikePicksheet', () => {
  it('accepts a real picksheet', () => {
    expect(() => assertLooksLikePicksheet(REAL_PICKSHEET, WEEK_ID)).not.toThrow()
  })

  it('classifies a logged-out page as an auth error, not a generic failure', () => {
    expect(() => assertLooksLikePicksheet(LOGGED_OUT, WEEK_ID)).toThrow(PicksheetAuthError)
  })

  it('classifies "no games yet" as not-ready — the caller must skip, not fail', () => {
    // Only an authenticated user is shown this page, so it must NOT be treated
    // as an auth failure, and must not be reported as a broken run.
    expect(() => assertLooksLikePicksheet(NO_GAMES_YET, WEEK_ID)).toThrow(PicksheetNotReadyError)
    expect(() => assertLooksLikePicksheet(NO_GAMES_YET, WEEK_ID)).not.toThrow(PicksheetAuthError)
  })

  it('rejects a CloudFront block page', () => {
    // Regression guard: 513 chars cleared the old `length < 100` check.
    expect(CLOUDFRONT_403.length).toBeGreaterThan(100)
    expect(() => assertLooksLikePicksheet(CLOUDFRONT_403, WEEK_ID)).toThrow(/WAF/i)
  })

  it('does not misclassify a WAF block as an auth or not-ready condition', () => {
    expect(() => assertLooksLikePicksheet(CLOUDFRONT_403, WEEK_ID)).not.toThrow(PicksheetAuthError)
    expect(() => assertLooksLikePicksheet(CLOUDFRONT_403, WEEK_ID)).not.toThrow(PicksheetNotReadyError)
  })

  it('rejects empty or whitespace-only responses', () => {
    expect(() => assertLooksLikePicksheet('', WEEK_ID)).toThrow(/empty/i)
    expect(() => assertLooksLikePicksheet('   \n  ', WEEK_ID)).toThrow(/empty/i)
  })

  it('rejects a page with too few spreads to be a picksheet', () => {
    expect(() => assertLooksLikePicksheet('Some page with only +1.5 on it', WEEK_ID))
      .toThrow(/does not look like a picksheet/i)
  })

  it('reports the offending weekId so logs identify the failing week', () => {
    expect(() => assertLooksLikePicksheet(LOGGED_OUT, 999)).toThrow(/999/)
  })
})
