/**
 * Validation for scraped picksheet text.
 *
 * Lives in its own module so both `fetch-picksheet.ts` and `login-session.ts`
 * use the exact same definition of "this is a real picksheet". A duplicated
 * copy is how the season-detection bug happened; not repeating that.
 *
 * History: the original guard was `text.length < 100`, which is a length floor,
 * not validation. A CloudFront "403 Request blocked" page (~513 chars) and a
 * "you need to be logged in" page (~20KB) both sailed through it, so the script
 * reported SUCCESS and would have stored an error page as the week's picksheet.
 */

/** A picksheet lists every game with spreads on both sides, so this is a low bar. */
const MIN_SPREADS = 6

const BLOCK_MARKERS = [
  '403 error',
  'request blocked',
  'access denied',
  'generated by cloudfront',
  'the request could not be satisfied'
] as const

const LOGIN_MARKERS = [
  'you need to be logged in',
  'please log in',
  'sign in to continue'
] as const

// The pool manager posts each week's schedule manually, so an authenticated
// request can legitimately land on a "nothing here yet" page. Only a logged-in
// user ever sees this, which makes it a reliable positive auth signal — and a
// reason to skip rather than fail.
const NOT_READY_MARKERS = [
  'no games for this week',
  'pool manager has set the schedule',
  'check back later'
] as const

export class PicksheetAuthError extends Error {}

/**
 * Authenticated, but the week has no schedule posted yet. Not a failure:
 * the caller should skip cleanly rather than report a broken run.
 */
export class PicksheetNotReadyError extends Error {}

function preview(text: string): string {
  return text.trim().slice(0, 140).replace(/\s+/g, ' ')
}

/**
 * Throws unless `text` actually looks like a picksheet.
 *
 * Distinguishes three non-picksheet outcomes so callers can react correctly:
 *   PicksheetAuthError     -> logged out; needs a human to re-login
 *   PicksheetNotReadyError -> logged IN, but no schedule posted yet; skip
 *   Error                  -> WAF block or genuinely unexpected content; fail
 */
export function assertLooksLikePicksheet(text: string, weekId: number): void {
  if (!text || !text.trim()) {
    throw new Error(`Empty response for weekId ${weekId}`)
  }

  const normalized = text.toLowerCase()

  const loginMarker = LOGIN_MARKERS.find(marker => normalized.includes(marker))
  if (loginMarker) {
    throw new PicksheetAuthError(
      `Not authenticated for weekId ${weekId} (page says "${loginMarker}"). ` +
      `The saved session is missing or expired — refresh it with: npm run login`
    )
  }

  const blockMarker = BLOCK_MARKERS.find(marker => normalized.includes(marker))
  if (blockMarker) {
    throw new Error(
      `Blocked by the site's WAF for weekId ${weekId} (matched "${blockMarker}"). ` +
      `This is usually headless-browser detection: confirm the stealth plugin is ` +
      `active. Response began: ${preview(text)}`
    )
  }

  // Checked before the spread count: this page has no spreads by definition,
  // and treating it as malformed would report a healthy run as broken.
  const notReadyMarker = NOT_READY_MARKERS.find(marker => normalized.includes(marker))
  if (notReadyMarker) {
    throw new PicksheetNotReadyError(
      `Authenticated, but weekId ${weekId} has no games posted yet ` +
      `(page says "${notReadyMarker}"). The pool manager has not set this ` +
      `week's schedule — nothing to fetch.`
    )
  }

  const spreadCount = (text.match(/[+-]\d+(?:\.\d+)?/g) || []).length
  if (spreadCount < MIN_SPREADS) {
    throw new Error(
      `Response for weekId ${weekId} does not look like a picksheet: found ` +
      `${spreadCount} spread-like values, expected at least ${MIN_SPREADS}. ` +
      `Response began: ${preview(text)}`
    )
  }
}
